name: los_parsimoniosos
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy>=1.26,<2.0
  - pandas>=2.2,<2.3
  - scipy>=1.11,<1.14
  - scikit-learn>=1.4,<1.5
  - matplotlib>=3.8
  - seaborn>=0.13
  - xgboost>=2.1
  - ipython
  - jupyter
  - jupyterlab
  - ipykernel
  - openpyxl
